Update

diff --git a/init.d/scripts/logstash b/init.d/scripts/logstash
--- a/init.d/scripts/logstash
+++ b/init.d/scripts/logstash
@@ -97,28 +97,37 @@ start() {
 }
 
 stop() {
-  # Try a few times to kill TERM the program
-  if status ; then
-    pid=$(cat "$pidfile")
-    trace "Killing $name (pid $pid) with SIGTERM"
-    kill -TERM $pid
-    # Wait for it to exit.
-    for i in 1 2 3 4 5 ; do
-      trace "Waiting $name (pid $pid) to die..."
-      status || break
-      sleep 1
-    done
-    if status ; then
-      if [ "$KILL_ON_STOP_TIMEOUT" -eq 1 ] ; then
-        trace "Timeout reached. Killing $name (pid $pid) with SIGKILL.  This may result in data loss."
-        kill -KILL $pid
-        emit "$name killed with SIGKILL."
-      else
-        emit "$name stop failed; still running."
-      fi
-    else
-      emit "$name stopped."
-    fi
+  ## Try a few times to kill TERM the program
+  #if status ; then
+  #  pid=$(cat "$pidfile")
+  #  trace "Killing $name (pid $pid) with SIGTERM"
+  #  kill -TERM $pid
+  #  # Wait for it to exit.
+  #  for i in 1 2 3 4 5 ; do
+  #    trace "Waiting $name (pid $pid) to die..."
+  #    status || break
+  #    sleep 1
+  #  done
+  #  if status ; then
+  #    if [ "$KILL_ON_STOP_TIMEOUT" -eq 1 ] ; then
+  #      trace "Timeout reached. Killing $name (pid $pid) with SIGKILL.  This may result in data loss."
+  #      kill -KILL $pid
+  #      emit "$name killed with SIGKILL."
+  #    else
+  #      emit "$name stop failed; still running."
+  #    fi
+  #  else
+  #    emit "$name stopped."
+  #  fi
+  #fi
+  echo "stopping.."
+  echo "stopping..${pidfile}"
+  #if [ -e ${pidfile} ] ; then
+  #     sudo kill -9 `cat ${pidfile}`
+  #fi
+  pid=`ps ax | grep -i '/apps/logstash/logstash-5.6.4/vendor/jruby/lib' | grep -v grep | awk '{print $1}'`
+  if [ -n "$pid" ]; then
+     sudo kill -9 $pid
   fi
 }
 
